name: Deploy Azure Function (Python)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'func-app/**'
      - '.github/workflows/deploy-function.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install func core tools
        run: |
          npm i -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNC_APP_NAME }}
          package: 'func-app'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISHPROFILE }}
    env:
      FUNC_APP_NAME: functionapp-func-4e87bd
